"""streamlitttttbq.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/132cQPCN_WH3-zLwwRNsAYUbVdufKJdb2
"""
import altair as alt
import numpy as np
import pandas as pd
import streamlit as st
from streamlit_option_menu import option_menu
import os

st.set_page_config(
        page_title="JohnLeggy",
)
class MultiApp:

    def __init__(self):
        self.apps = []

    def add_app(self, title, func):

        self.apps.append({
            "title": title,
            "function": function
        })

    def run():
        # app = st.sidebar(
        with st.sidebar:        
            app = option_menu(
                menu_title='JohnLeggy',
                options=['Home','Account','Trending','Ecommerce','GoogleAds','GA4'],
                icons=['house-fill','person-circle','trophy-fill','chat-fill','info-circle-fill'],
                menu_icon='chat-text-fill',
                default_index=1,
                styles={
                    "container": {"padding": "5!important","background-color":'black'},
        "icon": {"color": "white", "font-size": "23px"}, 
        "nav-link": {"color":"white","font-size": "20px", "text-align": "left", "margin":"0px", "--hover-color": "blue"},
        "nav-link-selected": {"background-color": "#02ab21"},}
                
                )

        
        if app == "Home":
            Home.app()
        if app == "Account":
            Account.app()    
        if app == "Trending":
            Trending.app()        
        if app == 'Ecommerce':
            Ecommerce.app()
        if app == 'GoogleAds':
            GoogleAds.app()    
        if app=='GA4':
            GA4.app()    
             
          
             
    run()
